### PR TITLE
Add support for loading js dependencies

### PR DESCRIPTION
**Pull request by antoinecomte**

### CODE REVIEW

**Comment by vmunier** [comment]
Hi @antoinecomte and thanks for the PR!

Instead of using a boolean value that the user has to update when they change the `skip in packageJSDependencies` value, we can be more dynamic and check that the jsdep file exist as a resource. Iff the resource exists, a `<script>` tag is added to include the jsdeps file.

I've just created a PR for that https://github.com/vmunier/play-scalajs-scripts/pull/2, you can leave comments on it if you've got suggestions :)

Vincent

**Comment by antoinecomte** [comment]
I fully agree that your solution is much better

**Comment by vmunier** [comment]
:+1: 

I'll publish a new version soon with https://github.com/vmunier/play-scalajs-scripts/pull/2 changes.

Closing this PR.

**Comment by antoinecomte** [comment]
Awesome

**Pull request closed without merging**
